#!/bin/sh
# Runs the release process

grep "<version>" pom.xml | head -1 | grep -q "RELEASE"
if [ $? -ne 0 ]; then
  echo "Current version is not *-RELEASE"
  echo "Please run .admin/update_version first"
  exit 1;
fi

git status | grep -q "nothing to commit, working tree clean"
if [ $? -ne 0 ]; then
  echo "Uncommitted files exists"
  exit 1;
fi;

curl -s https://api.travis-ci.com/tmobile/casquatch.svg?branch=`git rev-parse --abbrev-ref HEAD` | grep -q pass
if [ $? -ne 0 ]; then
  echo "Travis CI build is not passing"
  exit 1;
fi;

read -p "Please enter to stage for publishing"
git checkout -b tmp-release
git checkout master
git merge tmp-release
.admin/update_manual
read -p "Press enter after updating any final release notes"
git commit -a
git branch -D tmp-release
export GPG_TTY=$(tty)
mvn -P release-sign-artifacts clean deploy
echo "Release is now staged (https://oss.sonatype.org/#nexus-search;quick~casquatch). You must manually do:"
echo "mvn -P release-sign-artifacts nexus-staging:release"
echo "or"
echo "mvn -P release-sign-artifacts nexus-staging:drop"
echo "Finally run git push to push release changes to github"
