baseURL = "http://tmobile.github.io/casquatch"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Casquatch"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
    # Prefix URL to edit current page. Will display an "Edit this page" button on top right hand corner of every page.
    # Useful to give opportunity to people to create merge request for your doc.
    # See the config.toml file from this documentation site to have an example.
    editURL = "https://github.com/tmobile/casquatch/edit/master/manual/content/"
    # Author of the site, will be used in meta information
    author = "Josh Turner"
    # Description of the site, will be used in meta information
    description = "Documentation for Casquatch"
    # Shows a checkmark for visited pages on the menu
    showVisitedLinks = false
    # Disable search function. It will hide search bar
    disableSearch = false
    # Javascript and CSS cache are automatically busted when new version of site is generated.
    # Set this to true to disable this behavior (some proxies don't handle well this optimization)
    disableAssetsBusting = false
    # Set this to true to disable copy-to-clipboard button for inline code.
    disableInlineCopyToClipBoard = false
    # A title for shortcuts in menu is set by default. Set this to true to disable it.
    disableShortcutsTitle = true
    # When using mulitlingual website, disable the switch language button.
    disableLanguageSwitchingButton = true
    # Hide breadcrumbs in the header and only show the current page title
    disableBreadcrumb = true
    # Hide Next and Previous page buttons normally displayed full height beside content
    disableNextPrev = false
    # Order sections in menu by "weight" or "title". Default to "weight"
    ordersectionsby = "weight"
    # Change default color scheme with a variant one. Can be "red", "blue", "green".
    themeVariant = "casquatch"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "<i class='fas fa-bookmark'></i> API Docs"
url = "/docs"
weight = 10

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/tmobile/casquatch"
weight = 20